# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 24000
  - !type:CharacterDepartmentTimeRequirement
    department: Medical
    min: 38800
  - !type:CharacterPlaytimeRequirement
    tracker: JobMedicalDoctor
    min: 36000 # 10 hours
  - !type:CharacterPlaytimeRequirement
    tracker: JobChemist
    min: 36000 # 10 hours
  - !type:CharacterTraitRequirement
    inverted: true
    traits:
    - Foreigner
    - ForeignerLight
    - Muted
  - !type:CharacterEmployerRequirement
    employers:
    - ZengHuPharmaceuticals
    - Interdyne
    - NanoTrasen
  weight: 10
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Paramedic
  - External
  - Psychologist
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
    - type: SurgerySpeedModifier
      speedModifier: 2.5
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: CMOGear
  subGear:
  - CMOPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMO
    back: ClothingBackpackMedical
    shoes: ClothingShoesColorBrown
    id: CMOPDA
    ears: ClothingHeadsetAltMedical
  storage:
    back:
    - Flash

- type: startingGear
  id: CMOPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitCMO
    head: ClothingHeadEnvirohelmCMO
    gloves: ClothingHandsGlovesEnviroglovesWhite
