- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 24000
  - !type:CharacterDepartmentTimeRequirement
    department: Command
    min: 28800
  - !type:CharacterDepartmentTimeRequirement
    department: Security
    min: 28800
  - !type:CharacterDepartmentTimeRequirement
    department: Engineering
    min: 28800
  - !type:CharacterDepartmentTimeRequirement
    department: Medical
    min: 28800
  - !type:CharacterDepartmentTimeRequirement
    department: Epistemics
    min: 28800
  - !type:CharacterDepartmentTimeRequirement
    department: Logistics
    min: 28800
  - !type:CharacterDepartmentTimeRequirement
    department: Civilian
    min: 28800
  - !type:CharacterTraitRequirement
    inverted: true
    traits:
    - Foreigner
    - ForeignerLight
    - Muted
  - !type:CharacterEmployerRequirement
    employers:
    - NanoTrasen
    - IdrisIncorporated
  weight: 15
  startingGear: HoPGear
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Clerk
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Hydroponics
  - External
  - Cryogenics
  - Lawyer
  - Cargo
  - Orders
  - Mail
  - Salvage
  - Boxer
  - Clown
  - Library
  - Chapel
  - Research
  - Medical
  - Corpsman
  - Paramedic
  - Psychologist
  - Chemistry
  - Security
  - Engineering
  - Atmospherics
  - Mime
  - Musician
  - Reporter
  - Zookeeper
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: HoPGear
  subGear:
  - HoPPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpack
    shoes: ClothingShoesLeather
    id: HoPPDA
    ears: ClothingHeadsetHoP
  storage:
    back:
    - Flash

- type: startingGear
  id: HoPPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitHoP
    head: ClothingHeadEnvirohelmHoP
    gloves: ClothingHandsGlovesEnviroglovesHoP
